# ===================================================================
# 1. GENERAL APPLICATION CONFIGURATION
# ===================================================================
# Defines the network port for this microservice to avoid conflicts with port 8080
server.port=8085

# API path with versioning
app.api.path.bff=/api/v1/salesbff

#Logging level (sflf4j)
logging.level.com.salessystem.bff=DEBUG

# ===================================================================
# 2. Other services via feign
# ===================================================================
app.services.catalog.url=${CATALOG_URL:http://localhost:8081}
app.services.catalog.path=/api/v1/products
app.services.order.url=${ORDER_URL:http://localhost:8082}
app.services.order.path=/api/v1/orders

# ===================================================================
# 3. OpenAPI - enabled in DEV
# ===================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true