package com.salessystem.orderservice.integration;

import com.salessystem.orderservice.domain.Order;
import com.salessystem.orderservice.domain.OrderStatus;
import com.salessystem.orderservice.domain.SagaStatus;
import com.salessystem.orderservice.infra.persistence.OrderRepositoryGateway;
import com.salessystem.orderservice.integration.BaseIntegrationTest;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@Transactional // Rolls back database modifications after each test execution
@Sql(scripts = "/03 DB-ORDERS-test.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
class OrderRepositoryGatewayIT extends BaseIntegrationTest {

    @Autowired
    private OrderRepositoryGateway orderRepositoryGateway;

    @Test
    @DisplayName("Should successfully persist a domain Order and its items into real MariaDB container")
    void shouldSaveAndRetrieveOrderWithItems() {
        // Arrange: Build a clean domain order structure
        String uniqueCartUuid = UUID.randomUUID().toString();

        Order domainOrder = new Order();
        domainOrder.setUuid(uniqueCartUuid);
        domainOrder.setCustomerId(777);
        domainOrder.setStatus(OrderStatus.DRAFT);
        domainOrder.setInventoryStatus(SagaStatus.DRAFT);
        domainOrder.setPaymentStatus(SagaStatus.DRAFT);
        domainOrder.setTotalAmount(new BigDecimal("200.00"));
        domainOrder.setPriceUpdatedAt(LocalDateTime.now());

        // Adding items using your domain entity logic
        // Assumes addItem method links items correctly to the main entity model
        domainOrder.addItem(101, 2, new BigDecimal("50.00"));  // Total 100.00
        domainOrder.addItem(102, 1, new BigDecimal("100.00")); // Total 100.00

        // Act: Save to database using the clean architecture gateway port implementation
        Order savedDomainOrder = orderRepositoryGateway.save(domainOrder);

        // Assertions part 1: Validate returned domain model after insert execution
        assertThat(savedDomainOrder).isNotNull();
        assertThat(savedDomainOrder.getId()).isNotNull(); // ID must be auto-generated by DB
        assertThat(savedDomainOrder.getUuid()).isEqualTo(uniqueCartUuid);
        assertThat(savedDomainOrder.getItems()).hasSize(2);

        // Act: Attempt to retrieve the record back from DB using the secondary UUID index query
        Optional<Order> retrievedOrderOpt = orderRepositoryGateway.findByUuid(uniqueCartUuid);

        // Assertions part 2: Validate database physical read operations work seamlessly
        assertThat(retrievedOrderOpt).isPresent();
        Order databaseOrder = retrievedOrderOpt.get();

        assertThat(databaseOrder.getCustomerId()).isEqualTo(777);
        assertThat(databaseOrder.getStatus()).isEqualTo(OrderStatus.DRAFT);
        assertThat(databaseOrder.getTotalAmount()).isEqualByComparingTo(new BigDecimal("200.00"));

        // Assertions part 3: Confirm Cascade parameters store order items correctly
        assertThat(databaseOrder.getItems())
                .hasSize(2)
                .anySatisfy(item -> {
                    assertThat(item.getProductId()).isEqualTo(101);
                    assertThat(item.getQuantity()).isEqualTo(2);
                    assertThat(item.getPriceAtPurchase()).isEqualByComparingTo(new BigDecimal("50.00"));
                });
    }
}