# ===================================================================
# 1. GENERAL APPLICATION CONFIGURATION
# ===================================================================
# Defines the network port for this microservice to avoid conflicts with port 8080
server.port=8084

# API path with versioning
app.api.path.auth=/api/v1/customerauth

#Logging level (sflf4j)
logging.level.com.salessystem.catalogservice=DEBUG

# ===================================================================
# 2. DATABASE CONNECTION CONFIGURATION
# ===================================================================
# Database access credentials (using an application user created)
spring.datasource.username=${DB_APP_USER}
spring.datasource.password=${DB_APP_USER_PASSWD}

#MariaDB
spring.datasource.url=${MARIADB_URL:jdbc:mariadb://localhost:3306/db_customer_auth}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===================================================================
# 3. SPRING DATA JPA / HIBERNATE CONFIGURATION
# ===================================================================
# validate: changes to the database must be done with DBA approval, using DB scripts
spring.jpa.hibernate.ddl-auto=validate

# Enables logging of the actual SQL queries to the IntelliJ console
spring.jpa.show-sql=true

# Formats the logged SQL statements to make them readable and easy to debug
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# 3. Custom Application Properties for OAuth2 and JWT
# ===================================================================
jwt.secret: ${JWT_SECRET}
# 24 hours in milliseconds (dev)
jwt.expiration-ms: 86400000

github.client-id: ${GITHUB_CLIENT_ID}
github.client-secret: ${GITHUB_CLIENT_SECRET}
github.redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:8085/api/v1/salesbff/auth2/callback}

# ===================================================================
# 5. OpenAPI - enabled in DEV - but you need to allow it at SecurityConfig Class
# ===================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true