# ===================================================================
# 1. GENERAL APPLICATION CONFIGURATION
# ===================================================================
# Defines the network port for this microservice to avoid conflicts with port 8080
server.port=8083

# API path with versioning
app.api.path.orders=/api/v1/payments

#Logging level (sflf4j)
logging.level.com.salessystem.paymentservice=DEBUG

# ===================================================================
# 2. MYSQL DATABASE CONNECTION CONFIGURATION
# ===================================================================
# Connection URL
#spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/db_payment}

# Database access credentials (using an application user created)
spring.datasource.username=${DB_APP_USER}
spring.datasource.password=${DB_APP_USER_PASSWD}

# Defines the official MySQL JDBC driver class
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#MariaDB
spring.datasource.url=${MARIADB_URL:jdbc:mariadb://localhost:3306/db_payment}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===================================================================
# 3. SPRING DATA JPA / HIBERNATE CONFIGURATION
# ===================================================================
# validate: changes to the database must be done with DBA approval, using DB scripts
spring.jpa.hibernate.ddl-auto=validate

# Enables logging of the actual SQL queries to the IntelliJ console
spring.jpa.show-sql=true

# Formats the logged SQL statements to make them readable and easy to debug
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# 3. Apache Kafka
# ===================================================================
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:9092}

# TOPIC NAMES
app.kafka.topics.order-event=order-event
app.kafka.topics.payment-processed=payment-processed

#### Producer configs
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#### Consumer configs
spring.kafka.consumer.group-id=payment-group
#auto-offset-reset=earliest
spring.kafka.consumer.auto-offset-reset=earliest

# Key and value deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# 1. Activates deserializer with native treatment in Spring
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
# 2. The real serializer that should run
spring.kafka.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Serializer configs - JSON (Jackson)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.salessystem.paymentservice.adapters.inbound.messaging
# Sprint would try to find the class (from oder-service) that comes in the header. This config will avoid this.
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# ===================================================================
# 4. OpenAPI - enabled in DEV
# ===================================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true