# ===================================================================
# 1. GENERAL APPLICATION CONFIGURATION
# ===================================================================
# Defines the name of this specific microservice
spring.application.name=payment-service

#Defines which environment is currently active
spring.profiles.active=dev
