package com.salessystem.paymentservice.adapters.outbound.persistence;

import com.salessystem.paymentservice.domain.model.PaymentStatus;
import com.salessystem.paymentservice.domain.model.PaymentTransaction;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class PaymentPersistenceAdapterTest {

    @Mock
    private PaymentRepository repository;

    @InjectMocks
    private PaymentPersistenceAdapter adapter;

    private PaymentTransaction domainTransaction;
    private PaymentEntity jpaEntity;
    private Integer orderId;

    @BeforeEach
    void setUp() {
        // Given: Common test objects setup
        orderId = 123;

        domainTransaction = new PaymentTransaction();
        domainTransaction.setOrderId(orderId);
        domainTransaction.setCustomerId(456);
        domainTransaction.setTotalAmount(new BigDecimal("100.00"));
        domainTransaction.setPaymentToken("TOKEN_XYZ");
        domainTransaction.setStatus(PaymentStatus.SUCCESS);

        // Creating a matching entity to represent what the repository would handle
        jpaEntity = new PaymentEntity();
        jpaEntity.setOrderId(orderId);
        jpaEntity.setCustomerId(456);
        jpaEntity.setTotalAmount(new BigDecimal("100.00"));
        jpaEntity.setPaymentToken("TOKEN_XYZ");
        jpaEntity.setStatus(PaymentStatus.SUCCESS);
    }

    @Test
    @DisplayName("Should map all fields correctly to entity and save successfully")
    void shouldSavePaymentTransactionWithCorrectMapping() {
        // Given: We prepare the mock to return whatever entity it receives
        // (this keeps the test decoupled from hardcoded setup entities)
        when(repository.save(any(PaymentEntity.class))).thenAnswer(invocation -> invocation.getArgument(0));

        // When: Executing the adapter's save method
        PaymentTransaction result = adapter.save(domainTransaction);

        // Then: 1. Capture the entity that was actually generated by the Mapper inside the adapter
        ArgumentCaptor<PaymentEntity> entityCaptor = ArgumentCaptor.forClass(PaymentEntity.class);
        verify(repository, times(1)).save(entityCaptor.capture());

        PaymentEntity capturedEntity = entityCaptor.getValue();

        // 2. ASSERTIONS: Here we prove that the Mapper worked perfectly for EVERY field!
        assertThat(capturedEntity.getOrderId()).isEqualTo(domainTransaction.getOrderId());
        assertThat(capturedEntity.getCustomerId()).isEqualTo(domainTransaction.getCustomerId());
        assertThat(capturedEntity.getTotalAmount()).isEqualTo(domainTransaction.getTotalAmount());
        assertThat(capturedEntity.getPaymentToken()).isEqualTo(domainTransaction.getPaymentToken());
        assertThat(capturedEntity.getStatus()).isEqualTo(domainTransaction.getStatus());

        // 3. Verify the return mapping back to domain
        assertThat(result).isNotNull();
        assertThat(result.getOrderId()).isEqualTo(domainTransaction.getOrderId());
    }

    @Test
    @DisplayName("Should return Optional with domain object when payment is found by order ID")
    void shouldFindPaymentByOrderIdWithSuccess() {
        // Given: The repository finds the entity
        when(repository.findByOrderId(orderId)).thenReturn(Optional.of(jpaEntity));

        // When: Searching via adapter
        Optional<PaymentTransaction> resultOpt = adapter.findByOrderId(orderId);

        // Then: The Optional should be populated and mapped to domain correctly
        assertThat(resultOpt).isPresent();
        PaymentTransaction result = resultOpt.get();
        assertThat(result.getOrderId()).isEqualTo(orderId);
        verify(repository, times(1)).findByOrderId(orderId);
    }

    @Test
    @DisplayName("Should return empty Optional when payment is not found by order ID")
    void shouldReturnEmptyOptionalWhenPaymentNotFound() {
        // Given: The repository returns empty
        when(repository.findByOrderId(orderId)).thenReturn(Optional.empty());

        // When: Searching via adapter
        Optional<PaymentTransaction> resultOpt = adapter.findByOrderId(orderId);

        // Then: The result should be an empty Optional
        assertThat(resultOpt).isEmpty();
        verify(repository, times(1)).findByOrderId(orderId);
    }
}